const data = [
  {
    courseName: "Marketing",
    lessons: 9,
    duration: "17h 30m",
    title: "How to Market Yourself as a Coach or Consultant",
    totalRating: 10,
    instructor: "Mark Lassoff",
    originalPrice: "$19.00",
    discountedPrice: "$29.00",
    teacherProfile: "./assets/profile-images/course_author01.png",
    url: "./assets/course-images/course_thumb01.jpg",
  },
  {
    courseName: "Graphic Design",
    lessons: 5,
    duration: "12h 30m",
    title: "A Biginer Adobe Illustrator for Graphic Design",
    totalRating: 6,
    instructor: "David Millar",
    originalPrice: "$11.00",
    teacherProfile: "./assets/profile-images/course_author02.png",
    url: "./assets/course-images/course_thumb02.jpg",
  },
  {
    courseName: "Web Development",
    lessons: 8,
    duration: "14h 30m",
    title: "Become a Certified HTML, CSS, JavaScript Web Developer",
    totalRating: 8,
    instructor: "David Millar",
    originalPrice: "$29.00",
    teacherProfile: "./assets/profile-images/course_author03.png",
    url: "./assets/course-images/course_thumb03.jpg",
  },
  {
    courseName: "Development",
    lessons: 12,
    duration: "15h 30m",
    title: "Running a Web Development The Complete Guide",
    totalRating: 8,
    instructor: "David Millar",
    originalPrice: "$24.00",
    discountedPrice: "$15.00",
    teacherProfile: "./assets/profile-images/course_author04.png",
    url: "./assets/course-images/course_thumb04.jpg",
  },
  {
    courseName: "Photography",
    lessons: 10,
    duration: "12h 30m",
    title: "The Art of Seeing Photography training for the Artist in you",
    totalRating: 10,
    instructor: "David Millar",
    originalPrice: "$14.00",
    teacherProfile: "./assets/profile-images/course_author05.png",
    url: "./assets/course-images/course_thumb05.jpg",
  },
  {
    courseName: "Finance",
    lessons: 12,
    duration: "16h 30m",
    title: "The Complete Guide to the Global Capital Markets",
    totalRating: 14,
    instructor: "David Millar",
    originalPrice: "$22.00",
    teacherProfile: "./assets/profile-images/course_author06.png",
    url: "./assets/course-images/course_thumb06.jpg",
  },
];
